apiVersion: infra.modela.ai/v1alpha1
kind: Notifier
metadata:
  name: default-slack-notifier
  namespace: default-tenant
spec:
  owner: admin
  tenantRef:
    name: default-tenant
    namespace: modela-system
  connectionName: default-slack-connection

