apiVersion: infra.modela.ai/v1alpha1
kind: License
metadata:
  name: default-license
  namespace: default-tenant
spec:
  owner: admin
  tenantRef:
    name: default-teant
    namespace: modela-system
  secretRef: 
    name: default-license-secret
    namespace: default-tenant
  owner: admin
  email: ""
  maxProducts: 5
  maxTrainers: 1
  maxServers:  3
  maxUsers: 1
  maxDataPlanes: 1
  forecast: true
  nlp: false
  vision: false
  chatbot: false
  productName: "modela.ai free"
  priceName: "lite"
  notifierName:  default-email-notifier
  
