apiVersion: data.modela.ai/v1alpha1
kind: DataProduct
metadata:
  namespace: default-tenant
  name: iris-product
spec:
  gitLocation:
    gitConnectionName: default-git-repository
    url: ""
  tenantRef:
    name: default-tenant
    namespace: modela-system
  imageLocation:
    name: modela/iris-product
    registryConnectionName: default-dockerhub-connection
  dataLocation:
    bucketName: default-minio-bucket
    path: modela/live/dataproducts/iris
  servingSiteName: default-serving-site
  labName: default-lab
  task: binary-classification  
  defaultWorkloadClassName: cpu-1-mem-1gi 
  owner: admin
