apiVersion: v1
kind: Secret
metadata:
  name: no-one
  namespace: default-tenant
  labels:
    app.kubernetes.io/part-of: modela
    app.kubernetes.io/component: infra
type: Opaque
stringData:
  password: '$2a$14$d154O63mraxngBiKDbiUc.fZskDLOH9j1VZ9LCl9l3/4dIre/lRny'
---

apiVersion: infra.modela.ai/v1alpha1
kind: Account
metadata:
  name: no-one
  namespace: default-tenant 
spec:
  tenantRef:
    name: default-tenant
    namespace: modela-system
  type: "user"
  username: "no-one"
  firstName: "no"
  lastName: "one"
  email: "no-one@example"
  phone: "444-4444-444"
  
