apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: client
  namespace: modela-system
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/proxy-body-size: 8m
    nginx.org/proxy-connect-timeout: 30s
    nginx.org/proxy-read-timeout: 20s
    nginx.org/client-max-body-size: 50m
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/cors-allow-headers: "x-user-agent,x-grpc-web,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/add-base-url: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: modela-app.vcap.me
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: modela-frontend
                port:
                  number: 80
    - host: modela-api.vcap.me
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: modela-api-proxy
                port:
                  number: 8080
    - host: upload.vcap.me
      http:
        paths:
          - pathType: Prefix
            path: /upload
            backend:
              service:
                name: modela-data-dock
                port:
                  number: 8095
