apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modeld-data-plane
    app.kubernetes.io/part-of: modeld
  name: modeld-data-plane
  namespace: modeld-system
spec:
  replicas: {{ .Values.dataplane.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modeld-data-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modeld-data-plane
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'  
    spec:
      containers:
        - name: main
          image: "{{ .Values.dataplane.image.registry }}/{{ .Values.dataplane.image.repository }}:{{ .Values.dataplane.image.tag }}"
          imagePullPolicy: {{ .Values.dataplane.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9091
              name: metrics
            - containerPort: 8008
              name: profiling
          resources:
            limits:
              cpu: "{{.Values.dataplane.resources.limits.cpu}}"
              memory: "{{.Values.dataplane.resources.limits.memory}}"
            requests:
              cpu: "{{.Values.dataplane.resources.requests.cpu}}"
              memory: "{{.Values.dataplane.resources.requests.memory}}"
    
          volumeMounts:
            - name: data
              mountPath: /var/opt/modeld/data
          env:
            - name: CACHE_PATH
              valueFrom:
                  configMapKeyRef:
                    name: controlplane-configmap
                    key: cache-path


        - name: clouds
          image: "{{ .Values.clouds.image.registry }}/{{ .Values.clouds.image.repository }}:{{ .Values.clouds.image.tag }}"
          imagePullPolicy: {{ .Values.clouds.image.pullPolicy }}
          ports:
            - containerPort: 8090
              name: http
            - containerPort: 9091
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
            - name: data
              mountPath: /var/opt/modeld/data
          resources:
            limits:
              cpu: "{{.Values.clouds.resources.limits.cpu}}"
              memory: "{{.Values.clouds.resources.limits.memory}}"
            requests:
              cpu: "{{.Values.clouds.resources.requests.cpu}}"
              memory: "{{.Values.clouds.resources.requests.memory}}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: CACHE_PATH
              valueFrom:
                  configMapKeyRef:
                    name: controlplane-configmap
                    key: cache-path

      volumes:
        - name : data
          emptyDir: {}