apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modeld-data-plane
    app.kubernetes.io/part-of: modeld
  name: modeld-data-plane
  namespace: modeld-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modeld-data-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modeld-data-plane
    spec:
      containers:
        - name: main
          image: quay.io/metaprov/modeld-data-plane:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
          env:
            - name: HOST
              value:  "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: DEBUG
              value: "true"
            - name: ENV
              value:  "dev"
            - name: CACHE_PATH
              value: "/home/modeld/data"
            - name: CLOUDS_HOST
              value: "127.0.0.1"
            - name: CLOUDS_PORT
              value: "8090"



        - name: clouds
          image: quay.io/metaprov/modeld-clouds
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8090
          volumeMounts:
              - name: data
                mountPath: /home/modeld/data
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 10
          env:
            - name: HOST
              value:  "0.0.0.0"
            - name: PORT
              value: "8090"
            - name: DEBUG
              value: "true"
            - name: ENV
              value:  "dev"
            - name: CACHE_PATH
              value: "/home/modeld/data"
      volumes:
        - name : data
          emptyDir: {}