apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modeld-data-plane-metrics
    app.kubernetes.io/part-of: modeld
  name: modeld-data-plane-metrics
  namespace: modeld-system
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: modeld-data-plane