apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-proxy
    app.kubernetes.io/part-of: modeld
  name: modeld-api-proxy
  namespace: modeld-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-proxy
    app.kubernetes.io/part-of: modeld
  name: modeld-api-proxy
  namespace: modeld-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-proxy
    app.kubernetes.io/part-of: modeld
  name: modeld-api-proxy
  namespace: modeld-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modeld-api-proxy
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccount:modeld-system:modeld-api-proxy