apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-proxy
  name: modeld-api-proxy
  namespace: modeld-system
spec:
  ports:
    - name: grpc
      port: 8080
  selector:
    app.kubernetes.io/name: modeld-api-proxy
