namespace: modela-system


modela:
  debug: false
  cachePath: "/var/opt/modela/data"
  logAsJson: false
  imagePullSecrets: ""
  podAnnotations: { }
  revisionHistoryLimit: 10
  podSecurityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
  containerSecurityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
  ha:
      enabled: false
      replicaCount: 3
  mtls:
     enabled: true
     workloadCertTTL: 24h
     allowedClockSkew: 15m
  grafana:
    port: 3000
    enableRemoteRendering: false
  prometheus:
    # -- Prometheus port
    port: 7070
    retention:
      # -- Prometheus retention time
      time: 15d

minikube:
  enabled: true

certManager:
  enabled: true

rbac:
  create: true

podSecurityPolicy:
  enabled: false

deployment:
  updateStrategy:
      type: Recreate

apigateway:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: metaprov/modela-api-gateway
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

apiproxy:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: metaprov/modela-api-proxy
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

dbproxy:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: metaprov/modela-database-proxy
    tag: latest
    pullPolicy: Always    
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi


controlplane:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: metaprov/modela-control-plane
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limit:
      cpu: 400m
      memory: 128Mi

datadock:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: metaprov/modela-data-dock
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limit:
      cpu: 200m
      memory: 128Mi

dataplane:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: metaprov/modela-data-plane
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limit:
      cpu: 1000m
      memory: 1024Mi

frontend:
  replicaCount: 1
  image:
    registry: ghcr.io
    tag: latest
    repository: metaprov/modela-frontend
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limit:
      cpu: 200m
      memory: 256Mi


clouds:
  replicaCount: 1
  image:
    registry: ghcr.io
    tag: latest
    repository: metaprov/modela-cloud-proxy
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

ingress:
  name : modela-ingress
  host: modela.info
  enabled: true
  certManager: false
  tls: false

