kind: Service
apiVersion: v1
metadata:
  name: modeld-dataplane
  namespace: modeld-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: modeld-dataplane
