apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: modeld-data-dock
    app.kubernetes.io/part-of: modeld
  name: modeld-data-dock
rules:
  - apiGroups: ["infra.modeld.io"]
    resources:
      - virtualbuckets
      - connections
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: modeld-data-dock
    app.kubernetes.io/part-of: modeld
  name: modeld-data-dock
  namespace: modeld-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modeld-data-dock
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccount:modeld-system:modeld-data-dock
    namespace: modeld-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: modeld-data-dock
    app.kubernetes.io/part-of: modeld
  name: modeld-data-dock
  namespace: modeld-system