apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: compute-xlarge
  namespace: modela-catalog
spec:
  resourcesTemplate:
    workloadClassName:  compute-xlarge 
    requirements:      
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"  
  
  