apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: compute-large
  namespace: modela-catalog
spec:
  resourcesTemplate:
    workloadClassName:  compute-large
    requirements:
      requests:
        memory: "64Mi"
        cpu: "1500m"
      limits:
        memory: "128Mi"
        cpu: "2000m"  
