apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: compute-medium
  namespace: modela-catalog
spec:
  resourcesTemplate:
    workloadClassName:  compute-medium
    requirements:
        requests:
          memory: "64Mi"
          cpu: "1"
        limits:
          memory: "128Mi"
          cpu: "1"  
  
  