apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: general-2xlarge
  namespace: modela-catalog
spec:
  resourcesTemplate:
    workloadClassName:  general-2xlarge
    requirements:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"  
  
  