apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: cpu-1-mem-1gi
  namespace: modela-catalog
spec:
  dataImage: quay.io/metaprov/modela-data-plane:{{ .Chart.AppVersion }}
  controlImage: quay.io/metaprov/modela-workload:{{ .Chart.AppVersion }}
  trainerImage: quay.io/metaprov/modela-trainer:{{ .Chart.AppVersion }}
  publisherImage: quay.io/metaprov/modela-publisher:{{ .Chart.AppVersion }}
  vcpu: 1
  mem:  1Gi
  podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: modela-trainer
      spec:
        restartPolicy: Never
        containers:
          - name: control
            ports:
                - containerPort: 8080
            volumeMounts:
                - name: data
                  mountPath: /var/opt/modela/data
          - name: data
            image: quay.io/metaprov/modela-data-plane:{{ .Chart.AppVersion }}
            imagePullPolicy: Always
            ports:
               - containerPort: 8070
                 name: http
               - containerPort: 9090
                 name: metrics
               - containerPort: 8008
                 name: profiling
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1" 
            volumeMounts:
               - name: data
                 mountPath: /var/opt/modela/data
          - name: cloud-proxy
            image: quay.io/metaprov/modela-cloud-proxy:{{ .Chart.AppVersion }}
            imagePullPolicy: Always
            ports:
              - name: http
                containerPort: 8090
            volumeMounts:
              - name: data
                mountPath: /var/opt/modela/data
        volumes:
          - name: data
            emptyDir: {}