apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-gateway
    app.kubernetes.io/part-of: modeld
    app.kubernetes.io/component: infra
  name: modeld-api-gateway
  namespace: modeld-system
{{- if eq .Values.modeld.prometheus.enabled true }}
  annotations:
    prometheus.io/scrape: "{{ .Values.modeld.prometheus.enabled }}"
    prometheus.io/port: "{{ .Values.modeld.prometheus.port }}"
    prometheus.io/path: "/"
{{- end }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modeld-api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modeld-api-gateway
    spec:
      serviceAccountName: modeld-api-gateway
      containers:
        - name: main
          image: quay.io/metaprov/modeld-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
          livenessProbe:
              exec:
                command: ["/bin/grpc_health_probe", "-addr=:8080"]
              initialDelaySeconds: 10
          env:
            - name: AUTH_HOST
              value: "modeld-auth"
            - name: AUTH_PORT
              value: "8080"
            - name: FAKE
              value: "false"
            - name: HOST
              value:  "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: DEBUG
              value: "true"
            - name: ENV
              value: "dev"
            - name: CLOUDS_HOST
              value: "127.0.0.1"
            - name: CLOUDS_PORT
              value: "8090"
            - name: CACHE_PATH
              value: "/home/modeld/data"
            - name: DS_HOST
              value: modeld-data-plane
            - name: DS_PORT
              value: "8080"

        - name: clouds
          image: quay.io/metaprov/modeld-clouds
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
              - name: data
                mountPath: /home/modeld/data
          resources:
            limits:
              cpu: 250m
              memory: 300Mi
            requests:
              cpu: 250m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
             - name: GRPC_TRACE
               value: "all"
             - name:  GRPC_VERBOSITY
               value: "DEBUG"
             - name:  GRPC_GO_LOG_VERBOSITY_LEVEL
               value: "99"
             - name:  GRPC_GO_LOG_SEVERITY_LEVEL
               value: "info"
             - name:   HOST
               value:  "0.0.0.0"
             - name:   PORT
               value: "8090"
             - name:   DEBUG
               value: "false"
             - name: ENV
               value: "dev"
             - name: CACHE_PATH
               value: "/home/modeld/data"
      volumes:
       - name : data
         emptyDir: {}