apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-gateway
    app.kubernetes.io/part-of: modeld
  name: modeld-api-gateway
  namespace: modeld-system
rules:
  - apiGroups:
      - catalog.modeld.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - data.modeld.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - inference.modeld.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
    - infra.modeld.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - training.modeld.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
       - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - job
    verbs:
      - "*"
  - apiGroups:
     - "extensions"
     - "apps"
    resources:
     - deployments
    verbs:
      - "*"
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
      app.kubernetes.io/name: modled-api-gateway
      app.kubernetes.io/part-of: modeld
  name: modeld-api-gateway
  namespace: modeld-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modeld-api-gateway
subjects:
  - kind: ServiceAccount
    name: modeld-api-gateway
    namespace: modeld-system
---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-gateway
    app.kubernetes.io/part-of: modeld
  name: modeld-api-gateway
  namespace: modeld-system