apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modeld-api-gateway
    app.kubernetes.io/part-of: modeld
  name: modeld-api-gateway
  namespace: modeld-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: modeld-api-proxy