apiVersion: v1
kind: Service
metadata:
  name: modeld-apigateway
  namespace: modeld-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    modeld: modeld-apigateway
