apiVersion: catalog.modela.io/v1alpha1
kind: UserRoleClass
metadata:
  name: product-manager
  namespace: modela-catalog
spec:
  rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["pods"]
      verbs: ["get", "watch", "list"]