apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: decision-tree-regressor
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  task: regression
  frameworkName: scikit-learn
  categoricalParameters:
    - name:  criterion      
      enums:
        - gini
        - entropy
      defaultValue:  gini
  integerParameters:
    - name:   min_samples_split
      min: 2
      max: 2
      defaultValue: 2







