apiVersion: catalog.modeld.io/v1alpha1
kind: Algorithm
metadata:
  name: random-forest-regressor
  namespace: modeld-catalog
  labels:
    app.kubernetes.io/part-of: modeld
spec:
  frameworkName: scikit-learn
  task: regression
  floatParameters:
    - name: max_features
      min: 0
      max: 1
      defaultValue: 0.5
  integerParameters:
     - name: min_samples_split
       min: 2
       max: 20
       defaultValue: 2
     - name: min_samples_leaf
       min: 1
       max: 20
       defaultValue: 1
