apiVersion: apps/v1
kind: Deployment
metadata:
  name: modeld-datadock
  namespace: modeld-system
  labels:
      app: modeld-datadock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modeld-datadock
  template:
    metadata:
      labels:
          app: modeld-datadock
          app.kubernetes.io/name: {{ .Release.Name }}
          app.kubernetes.io/version: {{ .Values.modeld.tag }}
          app.kubernetes.io/component: datadock
          app.kubernetes.io/part-of: "modeld"
          app.kubernetes.io/managed-by: "helm"
  {{- if eq .Values.modeld.prometheus.enabled true }}
      annotations:
        prometheus.io/scrape: "{{ .Values.modeld.prometheus.enabled }}"
        prometheus.io/port: "{{ .Values.modeld.prometheus.port }}"
        prometheus.io/path: "/"
  {{- end }}
    spec:
      serviceAccountName: modeld-datadock
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.modeld.podSecurityContext | nindent 12 }}
      containers:
        - name: main
          image: {{ include "modeld.datadockImage" . }}
          imagePullPolicy: {{ .Values.modeld.pullPolicy | quote }}
          ports:
            - containerPort: 8095
              name: datadock
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
{{- with .Values.apigateway.extraEnv }}
          env:
            {{- toYaml . | nindent 14 }}
{{- end }}
{{- with .Values.apigateway.envFrom }}
          envFrom:
            {{- toYaml . | nindent 14 }}
{{- end }}
          securityContext:
            {{- toYaml .Values.modeld.containerSecurityContext | nindent 14 }}
{{- if .Values.datadock.resources }}
          resources: {{ toYaml .Values.datadock.resources | nindent 14 }}
{{- end }}
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10

        - name: clouds
          image: {{ include "modeld.cloudImage" . }}
          imagePullPolicy: {{ .Values.modeld.pullPolicy | quote }}
          ports:
            - containerPort: 8090
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
          resources:
              {{- toYaml .Values.clouds.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
{{- with .Values.apigateway.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
{{- end }}

    {{- with .Values.apigateway.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.apigateway.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    volumes:
      - name: data
        emptyDir: { }