apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: modeld-ingress
  namespace: modeld-system
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.global.tag }}
    app.kubernetes.io/component: modeld-ingress
    app.kubernetes.io/part-of: "modeld"
    app.kubernetes.io/managed-by: "helm"
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/proxy-body-size: 8m
    nginx.org/proxy-connect-timeout: 30s
    nginx.org/proxy-read-timeout: 20s
    nginx.org/client-max-body-size: 50m
    nginx.ingress.kubernetes.io/cors-allow-headers: "x-user-agent,x-grpc-web,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
spec:
  rules:
    - host: modeld.info
      http:
        paths:
          - path: /
            backend:
              serviceName: modeld-frontend
              servicePort: 8080
          - path: /upload
            backend:
              serviceName:  modeld-data-dock
              servicePort: 8080
    - host: api.modeld.info
      http:
        paths:
          - path: /
            backend:
              serviceName: modeld-api-proxy
              servicePort: 8080

