apiVersion: apps/v1
kind: Deployment
metadata:
  name: modeld-frontend
  namespace: modeld-system
  labels:
    app: modeld-frontend
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.global.tag }}
    app.kubernetes.io/component: modeld-data-plane
    app.kubernetes.io/part-of: "modeld"
    app.kubernetes.io/managed-by: "helm"
spec:
  selector:
    matchLabels:
      app: modeld-frontend
  template:
    metadata:
      labels:
        app: modeld-frontend
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.global.tag }}
        app.kubernetes.io/component: modeld-data-plane
        app.kubernetes.io/part-of: "modeld"
        app.kubernetes.io/managed-by: "helm"
    spec:
      serviceAccountName: modeld-service-account
      containers:
        - name: main
          image: "{{ .Values.global.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.global.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy | quote }}
          ports:
            - containerPort: 80
              name: frontend
            - containerPort: 8008
              name: profiling
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}


