apiVersion: apps/v1
kind: Deployment
metadata:
  name: modeld-frontend
  namespace: modeld-system
  labels:
      app: modeld-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: modeld-frontend
  template:
    metadata:
      labels:
        app: modeld-frontend
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.modeld.tag }}
        app.kubernetes.io/component: controlplane
        app.kubernetes.io/part-of: "modeld"
        app.kubernetes.io/managed-by: "helm"
  {{- if eq .Values.modeld.prometheus.enabled true }}
      annotations:
        prometheus.io/scrape: "{{ .Values.modeld.prometheus.enabled }}"
        prometheus.io/port: "{{ .Values.modeld.prometheus.port }}"
        prometheus.io/path: "/"
  {{- end }}
    spec:
      containers:
        - name: main
          image: {{ include "modeld.frontendImage" . }}
          imagePullPolicy: {{ .Values.modeld.pullPolicy | quote }}
          ports:
            - containerPort: 8080
              name: apigateway
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          {{- with .Values.frontend.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.modeld.containerSecurityContext | nindent 12 }}


