apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modeld.frontendFullname" . }}
  namespace: modeld-system
  labels:
  {{- include "modeld.frontendLabels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.modeld.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "modeld.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: modeld-dataplane
  {{- if eq .Values.modeld.prometheus.enabled true }}
      annotations:
        prometheus.io/scrape: "{{ .Values.modeld.prometheus.enabled }}"
        prometheus.io/port: "{{ .Values.modeld.prometheus.port }}"
        prometheus.io/path: "/"
  {{- end }}
    spec:
      containers:
        - name: main
          image: {{ include "modeld.frontendImage" . }}
          imagePullPolicy: {{ .Values.modeld.pullPolicy | quote }}
          ports:
            - containerPort: 8080
              name: apigateway
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          {{- with .Values.frontend.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.modeld.containerSecurityContext | nindent 12 }}


