kind: Service
apiVersion: v1
metadata:
  name: {{ include "modeld.frontendFullname" . }}
  namespace: modeld-system
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "modeld.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: modeld-frontend