apiVersion: infra.modela.ai/v1alpha1
kind: ModelaSystem
metadata:
  name: system
  namespace: modela-system
spec:
  release: {{ .Chart.AppVersion }}
  active: true
  images:
    controlPlane: {{ .Values.clouds.image.registry }}/metaprov/modela-control-plane :{{ .Chart.AppVersion }}
    datadock: {{ .Values.clouds.image.registry }}/metaprov/modela-datadock:{{ .Chart.AppVersion }}
    frontend: {{ .Values.clouds.image.registry }}/metaprov/modela-frontend:{{ .Chart.AppVersion }}
    publisher: {{ .Values.clouds.image.registry }}/metaprov/modela-publisher:{{ .Chart.AppVersion }}
    trainer: {{ .Values.clouds.image.registry }}/metaprov/modela-trainer:{{ .Chart.AppVersion }}
    batchPredictor: {{ .Values.clouds.image.registry }}/metaprov/modela-batch-predictor:{{ .Chart.AppVersion }}
    apiproxy: {{ .Values.clouds.image.registry }}/metaprov/modela-api-proxy:{{ .Chart.AppVersion }}
    dataplane: {{ .Values.clouds.image.registry }}/metaprov/modela-data-plane:{{ .Chart.AppVersion }}
    cloudproxy: {{ .Values.clouds.image.registry }}/metaprov/modela-cloud-proxy:{{ .Chart.AppVersion }}
    databaseProxy: {{ .Values.clouds.image.registry }}/metaprov/modela-database-proxy:{{ .Chart.AppVersion }}
    predictionRouter: {{ .Values.clouds.image.registry }}/metaprov/modela-prediction-router:{{ .Chart.AppVersion }}
    modelaSystem: {{ .Values.clouds.image.registry }}/metaprov/modela-supervisor:{{ .Chart.AppVersion }}
    modelaPredictionServer: {{ .Values.clouds.image.registry }}/metaprov/modela-prediction-server:latest
    modelaDashboardServer: {{ .Values.clouds.image.registry }}/metaprov/modela-datashboard-server:latest
    modelaWorkerControl:  {{ .Values.clouds.image.registry }}/metaprov/modela-workload:{{ .Chart.AppVersion }}
    apiGateway: {{ .Values.clouds.image.registry }}/metaprov/modela-apigateway:{{ .Chart.AppVersion }}
  podTemplate:
      metadata: 
        labels:
          app.kubernetes.io/name: modela-trainer
      spec:
        restartPolicy: Never
        containers:
          - name: control
            ports:
                - containerPort: 8080
            volumeMounts:
                - name: data
                  mountPath: /var/opt/modela/data
          - name: data
            image: ghcr.io/metaprov/modela-data-plane:v0.4.205
            imagePullPolicy: IfNotPresent
            ports:
               - containerPort: 8070
                 name: http
               - containerPort: 9090
                 name: metrics
               - containerPort: 8008
                 name: profiling
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1"
            volumeMounts:
               - name: data
                 mountPath: /var/opt/modela/data
          - name: cloud-proxy
            image: ghcr.io/metaprov/modela-cloud-proxy:latest
            imagePullPolicy: IfNotPresent
            ports:
              - name: http
                containerPort: 8090
            volumeMounts:
              - name: data
                mountPath: /var/opt/modela/data
        volumes:
          - name: data
            emptyDir: {}