apiVersion: catalog.modela.io/v1alpha1
kind: Algorithm
metadata:
  name: catboost
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  frameworkName: scikit-learn
  task: binary-classification