apiVersion: v2
name: modela-default-tenant
description: A Helm chart for default tenant
version: 0.4.418
appVersion: 0.4.417
icon: https://raw.githubusercontent.com/metaprov/modelaapi/main/static/imgs/logo/svg/symbol_horizontal_light.svg
keywords:
    - machine learning
    - automl
    - model
    - ai
home: https://www.modela.ai
sources:
    - https://github.com/metaprov/modelaapi    
type: application
maintainers:
    - name: Metaprov Inc
      email: info@metaprov.com

