apiVersion: infra.modeld.io/v1alpha1
kind: Tenant
metadata:
  name: default-tenant
  namespace: modeld-system
spec:
  defaultLabRef:
      name: default-lab
      namespace: default-tenant
  defaultServingSiteRef:
      name: default-serving-site
      namespace: default-tenant