apiVersion: infra.modeld.io/v1alpha1
kind: Notifier
metadata:
  name: default-slack-notifier
  namespace: default-tenant
spec:
  owner: admin
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  connectionName: default-slack-connection

