apiVersion: infra.modeld.io/v1alpha1
kind: ServingSite
metadata:
  name: default-serving-site
  namespace: default-tenant
spec:
  fdqn: {{ .Values.servingsite.fdqn }}
  tenantRef:
    name: default-tenant
    namespace: modeld-system
