apiVersion: infra.modeld.io/v1alpha1
kind: License
metadata:
  name: default-license
  namespace: default-tenant
spec:
  tenantRef:
    name: default-tenant
    namespace: {{ .Release.Namespace }}
  connectionName: default-license-credential
  secretName: default-licnese-secret
  type: lite
  notifierSelector:
    app: general

