apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-frontend
  name: modela-frontend
  namespace: modela-system
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-frontend
    spec:
      containers:
        - name: main
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.distribution }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          resources:        
            limits:
              cpu: "{{.Values.frontend.resources.limits.cpu}}"
              memory: "{{.Values.frontend.resources.limits.memory}}"
            requests:
              cpu: "{{.Values.frontend.resources.requests.cpu}}"
              memory: "{{.Values.frontend.resources.requests.memory}}"
      
           

