apiVersion: catalog.modela.ai/v1alpha1
kind: ManagedImage
metadata:
  name: modela-batch-predictor
  namespace: modela-catalog
spec:
  description: "modela batch predictor image"
  registry: "ghcr.io"
  repository: "metaprov/modela-batch-predictor"
  tag: "latest"
  role: "system"
  active: true
  maintainedBy: "Metaprov Inc"
  