{{ if .Values.dockerhub.create }}
apiVersion: v1
kind: Secret
metadata:
  name: default-dockerhub-secret
  namespace: default-tenant
  labels: {{- include "modela.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.digitalocean.secret.token }}
  host: {{ .Values.dockerhub.secret.registryHost | b64enc | quote }}
  {{ else }}
  host: {{ required "image registry host is required!" .Values.dockerhub.secret.registryHost }}
  {{- end }}
  {{- if .Values.dockerhub.secret.username }}
  username: {{ .Values.dockerhub.secret.username | b64enc | quote }}
  {{ else }}
  username: {{ required "image registry username is required!" .Values.dockerhub.secret.username }}
  {{- end }}
  {{- if .Values.dockerhub.secret.password }}
  password: {{ .Values.dockerhub.secret.password | b64enc | quote }}
  {{ else }}
  password: {{ required "image registry secret is required!" .Values.dockerhub.secret.password }}
  {{- end }}

---
apiVersion: infra.modela.ai/v1alpha1
kind: Connection
metadata:
  name: default-dockerhub-connection
  namespace: default-tenant
  labels: {{- include "modela.common.metaLabels" . | nindent 4 }}
spec:
  owner: admin
  provider: docker-hub
  tenantRef:
    name: default-tenant
    namespace: modela-system
  secretRef : 
    name: default-dockerhub-secret
    namespace: default-tenant
  category: docker-image-registry
  imageRegistry:
    host: hub.docker.com
    username: '[hidden]'
    password: '[hidden]'

{{ end }}