{{ if .Values.github.create }}
apiVersion: infra.modela.ai/v1alpha1
kind: Connection
metadata:
  name: {{ .Values.github.name }}
  namespace: default-tenant
  labels: {{- include "modela.common.metaLabels" . | nindent 4 }}
spec:
  owner: admin
  provider: github
  tenantRef:
    name: default-tenant
    namespace: modela-system
  secretName : default-github-secret
  category: git
---
apiVersion: v1
kind: Secret
metadata:
  name: default-github-secret
  namespace: default-tenant
  labels: {{- include "modela.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.github.secret.token }}
  token : {{ .Values.github.secret.token | b64enc | quote }}
  {{ else }}
  token : {{ required "github token is required!" .Values.github.secret.token }}
  {{- end }}
  {{- if .Values.digitalocean.secret.token }}
  username : {{ .Values.github.secret.username | b64enc | quote }}
  {{ else }}
  username : {{ required "github username is required!" .Values.github.secret.username }}
  {{- end }}
{{ end }}


