apiVersion: catalog.modela.io/v1alpha1
kind: PublicDataset
metadata:
  name: adult
  namespace: modela-catalog
spec:
  url: https://github.com/metaprov/modelaapi/tree/main/datasets/adult
  description: Predict whether income exceeds $50K/yr
  task: binary-classification
  dataUrl: https://raw.githubusercontent.com/metaprov/modelaapi/main/datasets/adult/adult.csv
  citation: "1994 Census database"
  rows: 48842
  columns: 14
  fileSize: 20000
  targetColumn:  ""
  imbalanced: false
