apiVersion: catalog.modeld.io/v1alpha1
kind: WorkloadClass
metadata:
  name: cpu-2-mem-2gi
  namespace: modeld-catalog
spec:
  dataImage: quay.io/metaprov/modeld-data-plane:latest
  controlImage: quay.io/metaprov/modeld-workload:latest
  trainerImage: quay.io/metaprov/modeld-trainer:latest
  publisherImage: quay.io/metaprov/modeld-publisher:latest
  vcpu: 2
  mem:  2Gi
  podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: modeld-trainer
      spec:
        restartPolicy: Never
        containers:
          - name: control
            ports:
                - containerPort: 8080
            volumeMounts:
                - name: data
                  mountPath: /var/opt/modeld/data
          - name: data
            image: quay.io/metaprov/modeld-data-plane:latest
            imagePullPolicy: Always
            ports:
               - containerPort: 8070
                 name: http
               - containerPort: 9090
                 name: metrics
               - containerPort: 8008
                 name: profiling
            resources:
              requests:
                memory: "2Gi"
                cpu: "2"
              limits:
                memory: "2Gi"
                cpu: "2"
            volumeMounts:
               - name: data
                 mountPath: /var/opt/modeld/data
          - name: cloud-proxy
            image: quay.io/metaprov/modeld-cloud-proxy:latest
            imagePullPolicy: Always
            ports:
              - name: http
                containerPort: 8090
            volumeMounts:
              - name: data
                mountPath: /var/opt/modeld/data
        volumes:
          - name: data
            emptyDir: {}