apiVersion: catalog.modela.io/v1alpha1
kind: WorkloadClass
metadata:
  name: nano-cpu-250m-mem-128mi
  namespace: modela-catalog
spec:
  dataImage: quay.io/metaprov/modela-data-plane:latest
  controlImage: quay.io/metaprov/modela-workload:latest
  trainerImage: quay.io/metaprov/modela-trainer:latest
  publisherImage: quay.io/metaprov/modela-publisher:latest
  vcpu: 0.25
  mem:  128Mi
  podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: modela-trainer
      spec:
        restartPolicy: Never
        containers:
          - name: control
            ports:
                - containerPort: 8080
            volumeMounts:
                - name: data
                  mountPath: /var/opt/modela/data
          - name: data
            image: quay.io/metaprov/modela-data-plane:latest
            imagePullPolicy: Always
            ports:
               - containerPort: 8070
                 name: http
               - containerPort: 9090
                 name: metrics
               - containerPort: 8008
                 name: profiling
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "250m"
            volumeMounts:
               - name: data
                 mountPath: /var/opt/modela/data
          - name: cloud-proxy
            image: quay.io/metaprov/modela-cloud-proxy:latest
            imagePullPolicy: Always
            ports:
              - name: http
                containerPort: 8090
            volumeMounts:
              - name: data
                mountPath: /var/opt/modela/data
        volumes:
          - name: data
            emptyDir: {}