apiVersion: v1
kind: Secret
metadata:
  name: default-redshift-secret
  namespace: default-tenant
type: Opaque
stringData:
  username: ''
  password: ''
---

apiVersion: infra.modeld.io/v1alpha1
kind: Connection
metadata:
  name: default-redshift-connection
  namespace: default-tenant 
spec:
  owner: admin
  provider: redshift
  category: database
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  secretName : default-redshift-secret
  redshift:
    host: ''
    port: 3000
    username: ''
    password: ''
    database: ''    
    url: ''
