{{- if eq .Values.aws.create true }}
apiVersion: v1
kind: Secret
metadata:
  name: default-aws-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.aws.secret.az }}
  az: {{ .Values.aws.secret.az | b64enc | quote }}
  {{ else }}
  az: {{ required "aws az is required!" .Values.azure.secret.az }}
  {{- end }}

  {{- if .Values.aws.secret.accessKey }}
  accessKey : {{ .Values.aws.secret.accessKey | b64enc | quote }}
  {{ else }}
  accessKey : {{ required "aws access key is required!" .Values.aws.secret.accessKey }}
  {{- end }}

  {{- if .Values.aws.secret.secretKey }}
  secretKey : {{ .Values.aws.secret.secretKey | b64enc | quote }}
  {{ else }}
  secretKey : {{ required "aws secret key is required!" .Values.aws.secret.secretKey }}
  {{- end }}
---

apiVersion: infra.modeld.io/v1alpha1
kind: Connection
metadata:
  name: default-aws-connection
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: aws
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  secretName : default-aws-secret
---
apiVersion: infra.modeld.io/v1alpha1
kind: VirtualBucket
metadata:
  name: default-aws-bucket
  namespace: default-tenant
spec:
  tenantRef:
    namespace: modeld-system
    name : default-tenant
  connectionName: default-aws-connection


{{ end }}

