{{ if .Values.digitalocean.create }}
apiVersion: v1
kind: Secret
metadata:
  name: default-digitalocean-secret
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.digitalocean.secret.token }}
  token: {{ .Values.digitalocean.secret.token | b64enc | quote }}
  {{ else }}
  token: {{ required "digitalocean token is required!" .Values.digitalocean.secret.token }}
  {{- end }}
  {{- if .Values.digitalocean.secret.spacesAccessSecret }}
  secretKey: {{ .Values.digitalocean.secret.spacesAccessSecret | b64enc | quote }}
  {{ else }}
  secretKey: {{ required "digitalocean spaces access secret is required!" .Values.digitalocean.secret.spacesAccessSecret }}
  {{- end }}
  {{- if .Values.digitalocean.secret.spacesAccessKey }}
  accessKey: {{ .Values.digitalocean.secret.spacesAccessKey | b64enc | quote }}
  {{ else }}
  accessKey: {{ required "digitalocean spaces access key is required!" .Values.digitalocean.secret.storageAccountName }}
  {{- end }}
  {{- if .Values.digitalocean.secret.region }}
  az: {{ .Values.digitalocean.secret.region | b64enc | quote }}
  {{ else }}
  az: {{ required "digitalocean region is required!" .Values.digitalocean.secret.region }}
  {{- end }}
---
apiVersion: infra.modeld.io/v1alpha1
kind: Connection
metadata:
  name: default-digitalocean-connection
  namespace: default-tenant
  labels: {{- include "modeld.common.metaLabels" . | nindent 4 }}
spec:
  provider: digitalocean
  tenantRef:
    name: default-tenant
    namespace: modeld-system
  secretName: default-digitalocean-secret
  category: cloud
  digitalocean:
    token: '[hidden]'
    accessKey: '[hidden]'
    secretKey: '[hidden]'
    defaultRegion: 'nyc3'

---
apiVersion: infra.modeld.io/v1alpha1
kind: VirtualBucket
metadata:
  name: default-digitalocean-bucket
  namespace: default-tenant
spec:
  tenantRef:
    namespace: modeld-system
    name : default-tenant
  connectionName: default-digitalocean-connection
{{ end }}