{{ if .Values.email.create }}
apiVersion: v1
kind: Secret
metadata:
  name: default-email-secret
  namespace: default-tenant
  labels: {{- include "modela.common.metaLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.email.secret.username }}
  username: {{ .Values.email.secret.username | b64enc | quote }}
  {{ else }}
  username: {{ required "email user name is required!" .Values.email.secret.username }}
  {{- end }}

  {{- if .Values.email.secret.password }}
  password: {{ .Values.email.secret.username | b64enc | quote }}
  {{ else }}
  password: {{ required "email secret required!" .Values.email.secret.password }}
  {{- end }}
---
apiVersion: infra.modela.ai/v1alpha1
kind: Connection
metadata:
  name: default-email-connection
  namespace: default-tenant
  labels: {{- include "modela.common.metaLabels" . | nindent 4 }}
spec:
  owner: admin
  provider: smtp
  tenantRef:
    name: default-tenant
    namespace: modela-system
  secretName : default-email-secret
  category: general
  smtp:
    host: ''
    port: 25
    userName: ''
    password: ''

{{ end }}
