apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: modeld-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: serving-cert
  namespace: modeld-system
spec:
  dnsNames:
    - modeld-control-plane-webhook.svc.cluster.local
    - modeld-control-plane-webhook.modeld-system.svc
    - modeld-control-plane-webhook
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert