apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modeld-control-plane
    app.kubernetes.io/part-of: modeld
  name: modeld-control-plane
  namespace: modeld-system
spec:
  replicas: {{ .Values.controlplane.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modeld-control-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modeld-control-plane
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'
    spec:
      serviceAccountName: modeld-control-plane
      containers:
        - name: main
          image: "{{ .Values.controlplane.image.registry }}/{{ .Values.controlplane.image.repository }}:{{ .Values.controlplane.image.tag }}"
          imagePullPolicy: {{ .Values.controlplane.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
            - name: webhook-server-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9091
              name: metrics
            - containerPort: 8008
              name: profiling
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          env:
            - name: CACHE_PATH
              valueFrom:
                configMapKeyRef:
                    name: controlplane-configmap
                    key: cache-path          
          resources:
            limits:
              cpu: "{{.Values.controlplane.resources.limits.cpu}}"
              memory: "{{.Values.controlplane.resources.limits.memory}}"
            requests:
              cpu: "{{.Values.controlplane.resources.requests.cpu}}"
              memory: "{{.Values.controlplane.resources.requests.memory}}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10

        - name: cloud-proxy
          image: "{{ .Values.clouds.image.registry }}/{{ .Values.clouds.image.repository }}:{{ .Values.clouds.image.tag }}"
          imagePullPolicy: {{ .Values.clouds.image.pullPolicy }}
          ports:
            - containerPort: 8090
              name: http            
          volumeMounts:
            - name: data
              mountPath: /home/modeld/data
          resources:
            limits:
              cpu: "{{.Values.clouds.resources.limits.cpu}}"
              memory: "{{.Values.clouds.resources.limits.memory}}"
            requests:
              cpu: "{{.Values.clouds.resources.requests.cpu}}"
              memory: "{{.Values.clouds.resources.requests.memory}}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: CACHE_PATH
              valueFrom:
                  configMapKeyRef:
                    name: controlplane-configmap
                    key: cache-path

        - name: db-proxy
          image: "{{ .Values.dbproxy.image.registry }}/{{ .Values.dbproxy.image.repository }}:{{ .Values.dbproxy.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: controlplane-configmap
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: controlplane-configmap
                  key: db-port
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: controlplane-configmap
                  key: db-port
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgresql-password


      volumes:
        - name: data
          emptyDir: {}
        - name: webhook-server-cert
          secret:
            secretName: webhook-server-cert