apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-data-dock-metrics
    app.kubernetes.io/part-of: modela
  name: modela-data-dock-metrics
  namespace: modela-system
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app.kubernetes.io/name: modela-data-dock