namespace: modeld-system


modeld:
  debug: false
  cachePath: "/home/modeld/data"
  logAsJson: false
  imagePullSecrets: ""
  podAnnotations: { }
  revisionHistoryLimit: 10
  podSecurityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
  containerSecurityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
  ha:
      enabled: false
      replicaCount: 3
  mtls:
     enabled: true
     workloadCertTTL: 24h
     allowedClockSkew: 15m
  grafana:
    port: 3000
    enableRemoteRendering: false
  prometheus:
    # -- Prometheus port
    port: 7070
    retention:
      # -- Prometheus retention time
      time: 15d

minikube:
  enabled: true

certManager:
  enabled: true

rbac:
  create: true

podSecurityPolicy:
  enabled: false

deployment:
  updateStrategy:
      type: Recreate

apigateway:
  replicaCount: 1
  image:
    registry: quay.io
    repository: metaprov/modeld-api-gateway
    tag: v0.3.42    
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "500m"
      memory: "512M"

apiproxy:
  replicaCount: 1
  image:
    registry: quay.io
    repository: metaprov/modeld-api-proxy
    tag: v0.3.58
    pullPolicy: IfNotPresent    
  resources:
    limits:
      cpu: "250m"
      memory: "512M"
    requests:
      cpu: "250m"
      memory: "512M"

archive:
  replicaCount: 1
  image:
    registry: quay.io
    repository: metaprov/modeld-archive
    tag: v0.3.58
    pullPolicy: IfNotPresent    
  resources:
    limits:
      cpu: "250m"
      memory: "512M"
    requests:
      cpu: "250m"
      memory: "512M"


controlplane:
  replicaCount: 1
  image:
    registry: quay.io
    repository: metaprov/modeld-control-plane
    tag: v0.3.58    
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "500m"
      memory: "512M"

datadock:
  replicaCount: 1
  image:
    registry: quay.io
    repository: metaprov/modeld-data-dock
    tag: v0.3.58    
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "200m"
      memory: "512M"
    requests:
      cpu: "200m"
      memory: "512M"

dataplane:
  replicaCount: 1
  image:
    registry: quay.io
    repository: metaprov/modeld-data-plane
    tag: v0.3.58    
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "1000m"
      memory: "1Gi"

frontend:
  replicaCount: 1
  image:
    registry: quay.io
    tag: v0.3.58    
    repository: metaprov/modeld-frontend
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "500m"
      memory: "512M"

clouds:
  replicaCount: 1
  image:
    registry: quay.io
    tag: v0.3.58    
    repository: metaprov/modeld-clouds
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

ingress:
  name : modeld-ingress
  host: modeld.info
  enabled: true
  certManager: false
  tls: false

