namespace: modeld-system

modeld:
  tag: v0.3.13
  registry: quay.io
  pullPolicy: IfNotPresent
  debug: false
  cachePath: "/home/modeld/data"
  logAsJson: false
  imagePullSecrets: ""
  podAnnotations: { }
  revisionHistoryLimit: 10
  podSecurityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
  containerSecurityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
  ha:
      enabled: false
      replicaCount: 3
  mtls:
     enabled: true
     workloadCertTTL: 24h
     allowedClockSkew: 15m
  grafana:
    port: 3000
    enableRemoteRendering: false
  prometheus:
    # -- Prometheus port
    port: 7070
    retention:
      # -- Prometheus retention time
      time: 15d

minikube:
  enabled: true

rbac:
  create: true

podSecurityPolicy:
  enabled: false

deployment:
  updateStrategy:
      type: Recreate

apigateway:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

apiproxy:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

controlplane:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

datadock:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

dataplane:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

frontend:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

clouds:
  replicas: 1
  image:
    tag: v0.3.13    
  resources:
    limits:
      cpu: "50m"
      memory: "512M"
    requests:
      cpu: "50m"
      memory: "32M"

ingress:
  name : modeld-ingress
  host: modeld.info
  enabled: true
  certManager: false
  tls: false

